version: '3.8'
services:
  postgres:
    image: postgres:15.7
    container_name: gntech-challenge-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - database:/var/lib/postgresql
    networks:
      - gntech-challenge

volumes:
  database:
    driver: local

networks:
  gntech-challenge:
    driver: bridge